project:
  type: website

website:
  title: "simple_quarto_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.ipynb
        text: About
      - href: slides/slides.ipynb
        text: Slides
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

bibliography: reference.bib



